### ISSUE TITLE
None vs exceptions in returns

### ISSUE THREAD

**Issue by binaryaaron** [fionapigott/tweet_parser#1]
As discussed, we should improve the exception and return handling for certain parts of the code. Per @jrmontag suggestion, perhaps we limit exceptions to areas where the code actually breaks and return `None` in areas where a non-required field is not present.

As an example, 

```.python
def get_geo_coordinates(tweet):
    """
    return the geo coordinates, if they are included in the payload
    else raise 'unavailable field' error
    """
    if "geo" in tweet:
        if tweet["geo"] is not None:
            if "coordinates" in tweet["geo"]:
                [lat, lon] = tweet["geo"]["coordinates"]
                return {"latitude": lat, "longitude": lon}
    raise(NotAvailableError("Geo coordinates are not included in this Tweet"))
```

could be changed to return `None` or `{}`.

**Comment by fionapigott** [comment]
Done.
Currently, the only time a getter will raise an error is if the user tries to get poll data from activity streams Tweets (poll data is currently unavailable in any activity streams formatted data).
